FROM debian:jessie

RUN apt-get update && apt-get install -y \
  ruby \
  default-jre \
  && rm -rf /var/lib/apt/lists/*

RUN gem install s3_website
RUN s3_website install

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
